name: Tag and Package

on:
  push:
    branches:
      - master
      - version_tagging

jobs:
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@topbox-rci'
      - name: tag new version if merged into master
        run: |
          VERSION_TAG=v$(jq -r .version package.json)
          git tag $VERSION_TAG
          HEADER=$(echo -n "ad-m:${{secrets.GITHUB_TOKEN}}" | base64)
          git -c http.extraheader="AUTHORIZATION: basic $HEADER" push origin $VERSION_TAG
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
